debug

diff --git a/ci b/ci
--- a/ci
+++ b/ci
@@ -49,8 +49,8 @@ cd "$BUILD_DIR"
 # Any error is fatal.
 set -e
 set -o pipefail
-echo "About to fail with exit 1"
-exit 1
+echo "About to fail with exit 255"
+exit 255
 # set -x # uncomment for debugging.
 
 UBUNTU_SCRIPT=https://raw.githubusercontent.com/project-everest/everest/master/ubuntu-from-scratch
