Added Vale CI

diff --git a/ci b/ci
--- a/ci
+++ b/ci
@@ -82,7 +82,7 @@ post_to_slack () {
     \"username\": \"dzomo\", \"text\": \"$2\", \
     \"icon_emoji\": \":water_buffalo:\"}" "$SLACK_FSTAR_WEBHOOK"
 }
-trap 'post_to_slack "#everest-build" ":heavy_exclamation_mark: \`$0 $@\` *failed* with error code: $?"' ERR
+# DFG COMMMENTED THIS OUT ###  trap 'post_to_slack "#everest-build" ":heavy_exclamation_mark: \`$0 $@\` *failed* with error code: $?"' ERR
 
 # Figure out the branch
 if [[ $BUILD_SOURCEBRANCHNAME != "" ]]; then
@@ -448,6 +448,19 @@ case "$1" in
     run_log_commit "everest_move" "everest-upgrade" "#everest-build" "project-everest/everest"
     ;;
 
+  vale-ci)
+    # Run vale ci - start in everest
+    if ! [ -x everest ]; then
+      echo "Not in the right directory"
+      exit 1
+    fi
+
+    # Set up build environment
+    nuget restore vale/tools/Vale/src/packages.config -PackagesDirectory vale/tools/FsLexYacc 
+
+    run_log_commit "scons.bat -C vale -j 4" "vale-build" "#vale-build" "project-everest/everest/vale"
+    ;;
+
   *)
     cat <<USAGE
 USAGE: $0 ACTION
@@ -459,6 +472,7 @@ ACTIONS:
   everest-ci
   everest-nightly-check
   everest-nightly-move
+  vale-ci
 
 REMARKS:
   Read this script's source code for more explanations. It has comments.
